services:
  postgres:
    image: postgres:16
    container_name: takalo-db
    environment:
      POSTGRES_DB: takalo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - takalo-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: takalo-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8081:8080"
    networks:
      - takalo-network

volumes:
  pgdata:

networks:
  takalo-network:
    driver: bridge
