spring.application.name=takalo
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# DataSource (commun)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (commun)
spring.jpa.hibernate.ddl-auto=validate

# Flyway (commun)
spring.flyway.enabled=true

# OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
