spring.application.name=takalo
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# DataSource (commun)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (commun)
spring.jpa.hibernate.ddl-auto=validate

# Flyway (commun)
spring.flyway.enabled=true
